# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 546195bb0afcc4db4de7ddb4092e070da180ad5d975112ffd41c93ac26090d6e6b79f10a925aedfb58f92d6fb5d13d4fdfc9674bb2698e9f2d81d322966d2310

test:
  secret_key_base: b5212b19c55470fadf4e812dfe4da434b4fb11e9ed23f9858df66f9132ee7eeaa7052396bdd0a1ea1280e07a017a67ab34d7e3eeed39df75803b5821009eee8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
